version: '3.8'
services:
  webapp:
    image: ghcr.io/marshmallow-eater/chemsys:latest
    container_name: chemsys-app
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - images:/images
    environment:
      - DATABASE_URL=${DATABASE_URL}

volumes:
  images:
