version: '3.8'
services:
  couchdb:
    image: couchdb:3.3.2
    container_name: chemsys-db
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    ports:
      - "${COUCHDB_PORT}:5984"
    volumes:
      - couchdb-data:/opt/couchdb/data
    restart: unless-stopped
volumes:
  couchdb-data:
    driver: local

